### PR TITLE
corrected database issue #58

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
You might want to wait with this PR a bit. Your proposed changes are incomplete. See ros-planning/moveit_setup_assistant#103.

I have a few PRs lined up to fix this for both Fanuc and ABB.

Just waiting for the PR to MSA being accepted.

**Comment by shaun-edwards** [comment]
@Levi-Armstrong, I think @gavanderhoorn is referring to the fact that `arg db` is not specified as an argument to the launch file (see the fanuc PR, [here](https://github.com/ros-industrial/fanuc/pull/143/files#diff-d0b11f69196a405b9a32bc36500d4314R18)).

@gavanderhoorn, it sounds like you will issue a proper fix once you PR to the `moveit_setup_assistant` is approved.

**Comment by gavanderhoorn** [comment]
@shaun-edwards: not just that. The changes in ros-industrial/fanuc#143 are incomplete as well, as they only allow to (dis,en)able the launching of the db. That is a work around: the real fix is to let the user specify a db location, otherwise setting `db:=true` for an installed package will still result in `Permission denied` errors.

Making the db location configurable is what ros-planning/moveit_setup_assistant#103 does.

>  it sounds like you will issue a proper fix once you PR to the `moveit_setup_assistant` is approved.

Yes. I'll basically back-port the fixes to the launch files.

**Comment by gavanderhoorn** [comment]
O and minor: but the commit msg of the commit in this PR is _Levi-Armstrong_ ;).

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn: Yea since I am new to github and have never used a repository hosting service, I was following an on-line tutorial which I figured was not correct but I was unable to find something that specified exactly what information was suppose to be contained in the commit message. If you don't mind providing your understanding of what information should be contained in the commit message, it would be appreciated since I am currently learning the process.

**Comment by shaun-edwards** [comment]
This was addressed in #60.

**Pull request closed without merging**
