### PR TITLE
Revert changes to tool0

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
- Revert pull request #67 
- Also added option to xacro to produce controller tool0

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn, @shaun-edwards: Is this a solution to keep the original tool0 but provide the option to create a urdf with the controller tool0?

**Comment by gavanderhoorn** [comment]
Interesting approach, but now the `irb_2400` macro itself requires an additional parameter (`controller_tool0`). Afaik, this breaks for users using the old one, but it is a 'visible' breakage, as `xacro` should print errors because of it.

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn, I am just going to revert them back to there original state; do you agree?

**Comment by gavanderhoorn** [comment]
If you are fixing up things for the Indigo release, perhaps we should create an `indigo-devel` branch and fix things there. Leave the deprecated pkgs here, on `hydro-devel`.

However, these transforms (the non-fixed ones) are just really incorrect, so it is essentially a bug-fix. If we communicate this properly (to the mailing list), I think we should be able to get away with this one, non-bw-compatible, change.

@shaun-edwards?

**Comment by shaun-edwards** [comment]
Just to get my head around this...We are reverting `abb_common` to the `hydro` state.  In `indigo-devel` this package will be removed as stated [here](https://github.com/ros-industrial/abb/blob/hydro-devel/abb_common/package.xml#L21).

**Comment by Levi-Armstrong** [comment]
I was attempting to propose a tool0 fix for the abb_common in the hydro_devel that was bw-compatible but the xacro does not have the capability to assign default values. Since the change was not bw-compatible the most recent commit would revert the changes made by #67.

**Comment by shaun-edwards** [comment]
OK...+1

**Comment by gavanderhoorn** [comment]
Please squash all commits in this PR into one before merging. No need to merge all attempts at fixing this issue into the main repository history.

**Comment by Levi-Armstrong** [comment]
@shaun-edwards, I missed one change I made to the irb 5400 which is corrected. Can you review it?

**Comment by shaun-edwards** [comment]
+1

**Pull request merged**
