### PR TITLE
Corrected missing axis 5b in wrist of irb_5400

### PR DESCRIPTION
**Pull request by dpsolomon**
Fixes issue #45

### CODE REVIEW

**Comment by shaun-edwards** [comment]
@dpsolomon, can you please update the new urdf (in the 5400 support package) created by PR #43.  A new URDF was created in order to maintain backwards compatibility.  Thanks in advance,

**Comment by dpsolomon** [comment]
Sure, it might be a day or two

**Comment by shaun-edwards** [comment]
ping?

**Comment by dpsolomon** [comment]
I should have a working system tonight. I didn't want to commit any changes without testing them...

**Comment by shaun-edwards** [comment]
ping?

**Comment by shaun-edwards** [comment]
ping @dpsolomon

**Comment by dpsolomon** [comment]
#!@!
Should I put all the changes only into the new irb5400 support package, or copy the changes to both the support and deprecated common packages?

**Comment by dpsolomon** [comment]
OK, new support package is updated. Obsolete abb_common package is updated locally (not included in pull request). If you want abb_common updated as well, it should just take a few moments to push (so judging historically, just 3-4 weeks ;) )

**Comment by dpsolomon** [comment]
Dare I ping? Not that I deserve to. This pull request is ready for review.

**Comment by gavanderhoorn** [comment]
@dpsolomon: I think `abb_common` should also get the changes, as it is still being released in Hydro, and the changes to the repository structure were meant to keep everything backwards compatible (at least, this is what I've been doing with deprecated packages living next to their replacements).

**Comment by dpsolomon** [comment]
ok, NOW it is ready. Changes are present and tested in both abb_irb5400_support and abb_common packages.

**Comment by shaun-edwards** [comment]
+1....thanks @dpsolomon for the contribution.

**Pull request merged**
