### PR TITLE
Support Package for ABB-IRB1200

### PR DESCRIPTION
**Pull request by geoffreychiou**
Also included is a fix for one of the packages not building with c++11.

@Levi-Armstrong @Jmeyer1292 , Please review.

### CODE REVIEW

**Comment by Jmeyer1292** [comment]
@geoffreychiou Did you pull the collision models from our Godel package?

**Comment by geoffreychiou** [comment]
@Jmeyer1292 I just copied the irb1200 support folder out of the kinetic-branch of Godel.

**Comment by Jmeyer1292** [comment]
I don't know about the `isnan` build issues on travis, but I can vouch that this robot support package has been used in conjunction with a robot that we have in our lab at SwRI and that we showed at Automate 2017.

**Comment by AustinDeric** [comment]
- [c++11 compiler flag is already in this repo for the 2400 moveit plugin package. ](https://github.com/ros-industrial/abb/blob/kinetic-devel/abb_irb2400_moveit_plugins/CMakeLists.txt#L3) Maybe @geoffreychiou needs to rebase this? I am surprised there aren't merge conflicts...

- [I added the irb 1200 to the abb_experimental repo kinetic-evel pull request.](https://github.com/ros-industrial/abb_experimental/pull/41) Which repo should the 1200 should go into?

- if you are using the `isnan` from the std library you need to reference it correctly `std::isnan` http://en.cppreference.com/w/cpp/numeric/math/isnan .

**Comment by geoffreychiou** [comment]
@AustinDeric Yup, I forgot to pull down the latest version before I added stuff in.

**Comment by AustinDeric** [comment]
I talked to Levi, the irb1200 should go here.  I will remove it from https://github.com/ros-industrial/abb_experimental

**Comment by gavanderhoorn** [comment]
My 2 cents, but new (support) packages should go into experimental repositories. That has been the convention / our policy for as long as we have github repositories. The fact that the package has been used for Automate does not mean it's fault-free. Putting things in an experimental repository allows others to expose your contributions to use-cases and contexts that it has not seen.

Packages in non-experimental repositories are expected to have gone through this process. It's sort of a seal-of-approval.

---

Btw: ros-industrial/abb_experimental#41 contains changes both for getting the repository to be releasable on Kinetic, as well as it adds a new support package, all in a single commit (ros-industrial/abb_experimental@ce643f66a9f356685b54157273b35c47123d5087). Splitting these kind of things in multiple commits is cleaner, as it does not mix different kinds of contributions and makes for easier reverts of things if needed in the future.

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn What is the official process for migrating the a robot from the experimental repo to the main repo?

**Comment by gavanderhoorn** [comment]
Depends on what you mean with 'official process'.

If you mean whether we have *objective metrics* for deciding when something should/could be moved, then I'm afraid we don't have any. It's subjective right now, as are the [Software Status](http://wiki.ros.org/Industrial/Software_Status) badges on the ROS wiki.

As for the technical side of things: I typically do what we did for `abb_resources` in #118 and ros-industrial/abb_experimental#39 (ie: remove in a single commit from experimental repo, then add in single commit to non-experimental repo while referencing the commit in the experimental repository in which you removed it). This does not import history of the artefacts involved, but as the exact commit that removed it from the remote repository is referenced, should allow anyone interested to follow that.

There are ways to import commits into repositories that would preserve history, but I've not really found a need to do that yet.

**Comment by Levi-Armstrong** [comment]
We have tested the current PR extensively over the past few weeks, and I am confident that it is correct. It sound like everything should go through the experimental repository, so we should merge it into the experimental and then in the near future migrate to the main repository?

**Comment by Levi-Armstrong** [comment]
I agree with @gavanderhoorn about splitting this up such that there is a single PR for each package.

**Comment by gavanderhoorn** [comment]
> It sound like everything should go through the experimental repository, so we should merge it into the experimental and then in the near future migrate to the main repository?

that's what the convention / policy has been so far, yes.

> We have tested the current PR extensively over the past few weeks, and I am confident that it is correct.

You are ultimately the maintainer of this repository, so it's your decision. I just wanted to clarify a bit what we typically do (ie: why the experimental repositories exist) as it seemed from the earlier comments that was a bit unclear.

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn, Thank you for clearing that up. 

@geoffreychiou Can you open up two PR against the experimental repository one for the urdf and one for the plugin?

**Comment by Jmeyer1292** [comment]
@Levi-Armstrong @gavanderhoorn Unless y'all come up with a written policy I'm strongly against the idea of putting it in the experimental repo. I don't want it to live in package purgatory indefinitely. This package hasn't seen updated packages in (2+) years and this robot has actually been tested.

The robots in the experimental repo also haven't been updated for two years.

**Comment by gavanderhoorn** [comment]
I didn't want to start an argument. I just explained what our (admittedly unwritten) policies have been so far. Personally I don't think we should change those but I'm not the only one deciding that.

As I wrote earlier, the whole idea of allowing some soak time is to expose packages to usage that it hasn't seen. I feel that is important, especially with things that we can't automatically test (like support packages).

But this is @Levi-Armstrong's repo, so he decides.

> The robots in the experimental repo also haven't been updated for two years.

so that would mean they can be migrated to the main repository.

**Comment by AustinDeric** [comment]
Hey *fellow humans*, developer discussions are best had on slack: 
http://rosindustrial.slack.com/

**Comment by gavanderhoorn** [comment]
@AustinDeric: would we not consider this part of the public discourse / discussion on 'best practices' in ROS-Industrial? Slack is private and inaccessible to our community.

**Comment by AustinDeric** [comment]
http://rosindustrial.slack.com/ is intended to be open to the public and a community tool.  It is invite only only to keep out the bots.  Also, anyone invited can then invite anyone.

**Comment by gavanderhoorn** [comment]
Ok. I was not aware of that. Thanks for clearing that up.

**Comment by geoffreychiou** [comment]
Opened new PR here: https://github.com/ros-industrial/abb_experimental/pull/43

**Pull request closed without merging**
