### PR TITLE
Add naming convention to the README.md

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@shaun-edwards & @gavanderhoorn Would either of you be so kind to review this PR?

**Comment by gavanderhoorn** [comment]
I was planning on reading through #75 once more to make sure we had everything covered. I'll do that later.

As to this PR: the text refers to a *Naming* section that doesn't exist.

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong: could you rebase the PR?

**Comment by Levi-Armstrong** [comment]
> As to this PR: the text refers to a Naming section that doesn't exist.

You are correct. I removed it.

**Comment by gavanderhoorn** [comment]
I've captured this in a (candidate) ROS-I REP. See [abb_naming/rep-ixxxx.rst](https://github.com/gavanderhoorn/rep-ros-i/blob/abb_naming/rep-ixxxx.rst).

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn, The rep looks good. I first thought there were a few spelling errors, but it looks like us Americans spell meters (metres) and centimeters (centimetres) different than the rest of the world. :)

**Comment by gavanderhoorn** [comment]
re: meters vs metres: yes, using BE gets me quite a nr of comments about spelling. Can't help it that you don't know how to properly spell ;)

**Comment by Levi-Armstrong** [comment]
What is the next step?

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn Let me know if there is anything I can help with.

**Comment by gavanderhoorn** [comment]
If we want to go with the REP, I'll just have to finish the motivation section, which should not be too hard.

I suggest we refer to the REP in the readme then.

**Comment by Levi-Armstrong** [comment]
I OK with moving forward with the REP.

**Comment by gavanderhoorn** [comment]
Ok. I've opened ros-industrial/rep#16.

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong: would you want to update this PR to make `readme.md` just link to [ros-industrial/rep/rep-I0007.rst](https://github.com/ros-industrial/rep/blob/master/rep-I0007.rst)?

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn Is this what you were expecting?

**Comment by gavanderhoorn** [comment]
Well, you're a maintainer here also, so is this what you would do? :)

+1 from me. The PR does need to be rebased though.

**Comment by Levi-Armstrong** [comment]
Opened new PR #125.

**Pull request closed without merging**
