### PR TITLE
Fix unresolved simple_message symbols at link time

### PR DESCRIPTION
**Pull request by Samsagax**
While building against Hydro with catkin_make_isolated this issue appears [1].
As a temporary workarround we need to add simple_message explicitly on each
binary using it

[1]https://github.com/ros-industrial/industrial_core/issues/68#issue-25999936

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
+1

This is indeed the same issue as described in ros-industrial/industrial_core#68.

**Comment by Samsagax** [comment]
Sorry for last 3 commits, those were intended for a different branch.

**Comment by gavanderhoorn** [comment]
Which is why it is good practice to create branches for pull requests :)

**Comment by Samsagax** [comment]
Should I commit the changes in a different branch and close this pull request, then?

**Comment by gavanderhoorn** [comment]
Well "should" may be a bit strong: it would avoid merging your accidental commit of those URDFs into `hydro-devel` though.

**Comment by Samsagax** [comment]
Ok, I'll close this pull request and do some git sorcery to send a clean pull request. I noticed some problems with the naming convention.

**Pull request closed without merging**
