### PR TITLE
Add manipulator irb-1600-1.2 model

### PR DESCRIPTION
**Pull request by Samsagax**
Added both urdf's and STL's for IRB-1600-1.2 manipulator. Will add moveit package soon.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@shaun-edwards: would we want to merge this into `abb` immediately? Perhaps `abb_experimental` first? We could also immediately make use of the support package layout then (see also #29).

**Comment by shaun-edwards** [comment]
@Samsagax - Have you verified this URDF using a physical robot (i.e. does the robot in rviz, match the arm configuration, joint orientations, etc...).

**Comment by Samsagax** [comment]
I have access to the physical robot And I'm able to check the URDF. I'll double check it tomorrow morning and also try to add a MoveIt package for the 1600. I'm somewhat concerned that the `tool0` frame of reference is not the same as the one configured in the actual manipulator. Should we invert that frame so the possitive Z-axis points outward of the flange?

**Comment by gavanderhoorn** [comment]
In general you should strive to make the URDF as close to the real thing as possible. If the ABB has the toolframe such that the Z points outward from the flange, then yes, `tool0` should do the same.

**Comment by Samsagax** [comment]
I copied the base URDF from the 2400 support package. I did not changed the orientations of any link or joint frames because both have the same 6-DOF, open kinematic chain architecture. The same approach goes for any other robot. 
The problem is that the 2400 also have the `tool0` frame wrong (and I'm assuming all models in this package have the same issue). That raises the issue of backwards compatibility if we change that in all robots. And also raises an issue with [ROS frame orientation guidelines](http://wiki.ros.org/Industrial/Tutorials/Create%20a%20URDF%20for%20an%20Industrial%20Robot).

Maybe we should discuss this in a different issue and perhaps the solution is trivial as adding something like `abb_tool0` with the correct orientation in all URDFs.

**Comment by shaun-edwards** [comment]
@Samsagax, I added an issue for the tool0 orientations mis-match.  Once you are sure the physical robot matches the URDF we can merge this pull request.  Until we address the tool0 orientation (see #32), we can pull this into `abb_experimental` (no need to open a new pull request, I can handle this part).

**Comment by Samsagax** [comment]
Just confirmed the URDF matches the physical robot. Also checked the MoveIt configuration.  Some changes must be added for using it on Hydro. Will add a pull request regarding that. You can close this one now, thanks.

On 13 de marzo de 2014 1:06:37 PM GMT-03:00, Shaun Edwards notifications@github.com wrote:

> @Samsagax, I added an issue for the tool0 orientations mis-match.  Once
> you are sure the physical robot matches the URDF we can merge this pull
> request.  Until we address the tool0 orientation (see #32), we can pull
> this into `abb_experimental` (no need to open a new pull request, I
> can handle this part).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ros-industrial/abb/pull/31#issuecomment-37551399

## 

Joaquín Ignacio Aramendía

**Pull request closed without merging**
