### PR TITLE
Remove deprecated package and dependencies for deprecated packages

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@shaun-edwards, I believe I found the issue with why bloom-release was not working. I did not remove the dependencies from abb/package.xml. I also missed the deprecated package abb_moveit_plugins. Once these changes are accepted the release should work.

**Comment by shaun-edwards** [comment]
+1. FYI...I normally don't do PRs for small release issues.  It slows things down.

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong: may I suggest you prepare releases in the `-devel` branch (updating changelogs, adding release artefacts, etc)? Then to do the release from the `DISTRO` branch, you only need to do a simple PR pulling in the state of the `-devel` branch. This keeps your history clean (no PRs from `DISTRO` to `-devel` and back), is trivial to manage, and makes the workflow completely clear.

**Comment by shaun-edwards** [comment]
@gavanderhoorn, the reason I have not done this in the past is because release artifacts, like version bumps and change logs, require a commit.  I've always felt it was better to do the commits on the release branch.  That way, if there were any changes that required review, I could do a PR back to the devel branch.  If anything was found in the PR, we could catch it and then update the release.

**Comment by gavanderhoorn** [comment]
It's not that big of a deal, I just thought I'd make the suggestion. I've always used pre-release tests to catch any mistakes before releases. Also, I consider the `-devel` branch to be where the work takes place. The release branch should then be relatively 'calm', and only sync with `-devel` at certain points in time (ie: whenever there is a release).

**Pull request merged**
