### PR TITLE
Indigo Release 1.2.1

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn, Can you please review when available?

**Comment by gavanderhoorn** [comment]
You're just syncing `indigo-devel` with `indigo` correct? Merging back release metadata (changelogs etc) through a PR does not need a review. Unfortunately we can't configure Github to only block certain PRs requiring a review, so +1.

**Review by gavanderhoorn — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Wow, almost clicked *Delete branch*:

sshot

**Comment by Levi-Armstrong** [comment]
Thank you. 

>Wow, almost clicked Delete branch:

That would have not been good.

**Pull request merged**
