### PR TITLE
Added URDF and moveit package for ABB IRB6640 robot

### PR DESCRIPTION
**Pull request by bakupers**
After review of the previous pull request by my colleague Simon, we decided to change our IRB 6640 packages to adhere to the naming convention used in the other ABB packages. Since that meant renaming most of the files and making a lot of small changes, we decided to make a new pull request.

Note that this is the IRB6640 185/2.8 version.
Note that the meshes of the visual model are quite large (>10MB)

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Just browsing through your package I noticed that some of the meshes seem to have some errors (missing or extra faces, vertices in strange places, incorrect face normals). In particular the meshes in the `visual` subdirectory (I haven't checked those in `collision`), files `LINK_1.stl`, `LINK_3.stl`, `LINK_4.stl` and `PISTON.stl`. This can be easily seen when opening the files in Meshlab, for instance.

Seeing as these meshes are also used in collision detection, it might be worthwhile to look into this?

**Comment by bakupers** [comment]
There are indeed some small errors in the visual meshes, however, the meshes that are used for collision detection are convex hulls, so they do not have this problem. We focussed on checking the collision meshes for these kinds of errors because, as you say, they are important for collision detection. We did not remove small errors from the visual meshes, because they are only used in visualization.

**Comment by gavanderhoorn** [comment]
Right, you are correct about the convex hulls. Most visual errors are quite minor, `LINK_1.stl` contains some large extraneous vertices though, might be easy to fix?

**Comment by shaun-edwards** [comment]
@bakupers, thanks for the contribution.  Looks good, I just had a few comments/questions before I pull in the change:
1. Can please verify that the joint limits have been checked against a "real" (physical or robot studio) robot?
2. Some of the collision models are quite detailed (i.e. not convex hulls).  Is there a reason for this?
3. The base should be named base_link, not link_base.  I know this probably isn't obvious, the main reason for this has to do with ROS conventions.  Most ROS tools are set up to recognize base_link as the origin. I can fix this when I do the pull request if you don't have time to change it.

**Comment by bakupers** [comment]
Dear Shaun,
1. I've re-checked all the joint limits. They correspond to the ABB spec sheets.
2. I've made convex hulls of all the collision meshes. There was no specific reason not to do this.
3. I've changed the name from link_base to base_link in all the necessary files

Kind regards,
Berend Kupers
Alten Mechatronics

**Comment by gavanderhoorn** [comment]
@bakupers: I hate to be 'that guy' again, but the convex hulls you've included in 97faed6 have inconsistent face normals (ie: some point inwards, others point outwards). I'm not sure, but apart from visualisation problems, this could lead to difficulties with the collision detection algorithms. In other packages we've tried to make sure all normals point outwards.

Meshlab has some tools to correct this, but you might run into other problems (non-manifold edges, etc).

**Comment by shaun-edwards** [comment]
@gavanderhoorn, I'm appreciate that you are that guy.

@bakupers, let me see if I can fix this problem first.  It will take longer for me to describe the fix than to just do it.

**Comment by shaun-edwards** [comment]
I fixed the face/normal orientation and manually merged the result.

**Pull request merged**
