### PR TITLE
Pulling release changes into devel branch.

### PR DESCRIPTION
**Pull request by shaun-edwards**

### CODE REVIEW

**Comment by shaun-edwards** [comment]
@jrgnicho, please review.

**Comment by jrgnicho** [comment]
@shaun-edwards  please review comments

**Comment by shaun-edwards** [comment]
> Have we not standardized having a 'home' position?

Not accordig to [here](http://wiki.ros.org/Industrial/Tutorials/Create_a_MoveIt_Pkg_for_an_Industrial_Robot).

> Is there a rule for how choose the new version number or is it somewhat arbitrary?

The change to catkin messed things up a little bit, since it requires all packages in a repo to have the same version (even a package is supposed to be a releasable unit).  For use revion, A.B.C, A is a major update/rewrite, B is a minor update, C is a patch.

**Comment by jrgnicho** [comment]
+1

**Pull request merged**
