### PR TITLE
Issue 24 catkin include

### PR DESCRIPTION
**Pull request by shaun-edwards**
See issue #24

### CODE REVIEW

**Comment by shaun-edwards** [comment]
@jrgnicho, can you review?

**Comment by jrgnicho** [comment]
Was the include removed because the code in this package is not meant to be used as a library?

**Comment by shaun-edwards** [comment]
Yes.  Only executables are built, no libraries.  The header would be useless without a library file to link against.

**Comment by jrgnicho** [comment]
These changes are fine with me but even though they're minor it looks like it will required to do a manual merge.
+1

**Pull request merged**
