### PR TITLE
IRB4400 transfer from experimental 

### PR DESCRIPTION
**Pull request by Jmeyer1292**
See title. Copy pasted into this repo.

See https://github.com/ros-industrial/abb_experimental/pull/59.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
It would be nice if you could update the commit msg for f82d94b (after ros-industrial/abb_experimental#59 is merged) to refer to the commit in which `abb_irb4400_support` is removed from `ros-industrial/abb_experimental`.

**Comment by gavanderhoorn** [comment]
Also: could we drop the `.urdf` please? That is only there because xacro support was not ubiquitous, but we shouldn't keep those around anymore.

**Comment by Jmeyer1292** [comment]
Removed URDF file.

Added 4400 package to the meta-package manifest.

**Comment by gavanderhoorn** [comment]
We don't want to refer to the commit in `ros-industrial/abb_experimental` where the pkg was removed (thumbs down)?

**Comment by Jmeyer1292** [comment]
It doesn't matter, at least to me. The history of the transfer is here in Github. If you'd like to add that later, I won't be offended.

**Comment by gavanderhoorn** [comment]
I can't edit your commit message, at least not without force-pushing to the repository. So that would not be possible.

**Comment by Jmeyer1292** [comment]
Good to go?

**Comment by Levi-Armstrong** [comment]
>It would be nice if you could update the commit msg for f82d94b (after ros-industrial/abb_experimental#59 is merged) to refer to the commit in which abb_irb4400_support is removed from ros-industrial/abb_experimental.

@gavanderhoorn Can we as maintainers do this by using the GitHub option *Create Merge Commit* and add the information then?

**Comment by gavanderhoorn** [comment]
Yes, that would be a way to get that hash referenced.

**Comment by Levi-Armstrong** [comment]
OK, I will merge this and reference the commit hash.

**Pull request merged**
