### PR TITLE
Fix #48: added default true for J23_coupled for 5400

### LINKED ISSUE #48: irb5400: add missing coupling factor parameter to support launch files
As per subject.

Even though the driver now defaults to `false` for the `J23_coupled` parameter, the correct value should still be added to (or at least documented in) the appropriate launch files in the IRB 5400 support package.

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by shaun-edwards** [comment]
I assume you have verified that the 5400 has coupled joints?

**Comment by gavanderhoorn** [comment]
According to @JeremyZoss (in his [comment](https://github.com/ros-industrial/abb/pull/43#issuecomment-47366422) on PR 43):

> - IRB5400 = false? (currently undefined)

**Comment by Levi-Armstrong** [comment]
I checked a few but not all version using RobotStudio and they had J23 coupling.

**Comment by gavanderhoorn** [comment]
Strange. Well @JeremyZoss wasn't too sure, it appears from his comment in PR 43.

**Comment by gavanderhoorn** [comment]
`J23_coupled:=true` was confirmed to be correct?

**Comment by Levi-Armstrong** [comment]
It was confirmed by RobotStudio.

On Sun, Mar 1, 2015 at 3:21 AM, G.A. vd. Hoorn notifications@github.com
wrote:

> J23_coupled:=true was confirmed to be correct?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-industrial/abb/pull/68#issuecomment-76589237.

## 

Levi Armstrong

**Pull request merged**
