### PR TITLE
Fix #32: corrects tool0 to match robot controller

### LINKED ISSUE #32: URDF tool0 frames do not match the ABB tool0 orientation.
There is/was some ambiguity in the ROS-Industrial documentation about the tool0 frame (see [here](http://wiki.ros.org/Industrial/Tutorials/Create%20a%20URDF%20for%20an%20Industrial%20Robot)).  The original intent of tool0 was to match exactly (pose & orientation) of the robot tool0.  This would allow a comparison between ROS-I reported positions and controller positions for tool0.  However, due to conflicting requirements for creating URDF (i.e. a preferred orientation of frames), the tool0 has not always matched the robot controller frame.
Reference: #31

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
```
- A link mount_flange is added in the kinematic chain between link_6 and tool0.
- The link orients the frame to match the robot controller allowing tool0 to match
   the robot controller tool0 exactly.
```

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@shaun-edwards, @gavanderhoorn: In the documentation http://wiki.ros.org/Industrial/Tutorials/Create%20a%20URDF%20for%20an%20Industrial%20Robot it states that tool0 frame shall match exactly the tool0 defined on the robot controller. Is the intent that additional tools have a child link of tool0 or are they to have the same child link as tool0?

**Comment by shaun-edwards** [comment]
It's not required that all tools link through `tool0`, but this might be helpful given that most MoveIt config packages specify the kinematic chain through `tool0` (I'm not sure on this).

As near as I can tell, the `mount_flange` is just an intermediate frame that results in `tool0` having all zero orientation/positions.  Could `tool0` just use the position/orientation of `mount_flange`?

**Comment by Levi-Armstrong** [comment]
@shaun-edwards:  The tool0 could use the position/oreintation of mount_flange but if you wanted to add another tool frame to the urdf, its parent link must be tool0 for both the urdf define tool frame and robot controller tool frame to match. So if you wanted everything match the robot controller include the user defined tool frame then tool0 must always be the parent link of all urdf tool frames. 

I assumed you would replace tool0 with a user defined tool frame from the robot controller and they would always match. Either way the end result is the same, it depends on what tool0 was intended to represent. A tool frame place holder or the last link in the kinematic chain of the robot to which tool frames are added.

I am leaning toward the last link in the kinematic chain of the robot to which tool frames are added definition because not all industrial robots define it at the mounting flange, keeping it generic.

**Comment by gavanderhoorn** [comment]
@shaun-edwards wrote:

> It's not required that all tools link through `tool0`, but this might be helpful given that most MoveIt config packages specify the kinematic chain through `tool0` (I'm not sure on this).

At least for the MoveIt cfgs, this is true, if they were created following the [ros-i tutorial](http://wiki.ros.org/Industrial/Tutorials/Create_a_MoveIt_Pkg_for_an_Industrial_Robot).

Something else which is influenced by this are the ikfast plugins: they only work ok if the chain they are asked to solve for is the same as for which they were generated. At least for all plugins I've created, this has been `base_link`->`tool0`.

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong: I always attach my eef urdfs _to_ `tool0`, and leave `tool0` to coincide with the _default_ TCP of the controller (so without any tool frame (or whatever it is called on that particular ctrlr)). Any additional tool frames are then children of `tool0`. I think that makes the most sense, as fi ikfast plugins keep working that way.

New tool frames (TCPs) can then either be added as additional frames in the urdf, or published outside of it using TF.

Updating `tool0` would mean that I have to create a copy of the manipulator URDF, which then becomes my responsibility to keep up-to-date with any changes that might be released for the original. Using `tool0` as the mounting point and some xacro include statements avoids this.

Edit: seems I'm essentially treating `tool0` as @Levi-Armstrong's `mount_flange`.

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong: did you deliberately not apply this to the urdfs in `abb_common`?

And I noticed that in 24f5530 you also removed the `calibration` and `dynamics` elements from all of the joints. I'm not sure, but should we perhaps have done that in a _tick-tock_ fashion?

Just trying to make sure we don't remove things that someone may be using.

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn: I did not deliberately not apply it to them, I just was focused on the packages for the indigo release and forgot that they were also in the abb_common. I will submit another pull request to fix those.

I understand that the standard practice is perform updates in a tick-tock fashion, but based on the discussion for this pull request [abb_experiments Pull #9](https://github.com/ros-industrial/abb_experimental/pull/9) stating that these are never used. I figured in this case there was no need to submit two different pull request.

**Comment by gavanderhoorn** [comment]
> I understand that the standard practice is perform updates in a tick-tock fashion, but based on the discussion for this pull request [abb_experiments Pull #9](https://github.com/ros-industrial/abb_experimental/pull/9) stating that these are never used. I figured in this case there was no need to submit two different pull request.

I would have preferred it if we had had a separate PR.

Also: they are probably never used, but we can never know, as users obviously don't tell us how they are using these packages.

**Comment by Levi-Armstrong** [comment]
I understand, I will make sure to do that next time.

On Fri, Feb 20, 2015 at 5:14 AM, G.A. vd. Hoorn notifications@github.com
wrote:

> I understand that the standard practice is perform updates in a tick-tock
> fashion, but based on the discussion for this pull request abb_experiments
> Pull #9 https://github.com/ros-industrial/abb_experimental/pull/9
> stating that these are never used. I figured in this case there was no need
> to submit two different pull request.
> 
> I would have preferred it if we had had a separate PR.
> 
> Also: they are probably never used, but we can never know, as users
> obviously don't tell us how they are using these packages.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-industrial/abb/pull/64#issuecomment-75222726.

## 

Levi Armstrong

**Pull request merged**
