### PR TITLE
Merge abb_irb1200_basic_support into indigo-devel

### PR DESCRIPTION
**Pull request by oliverek12**
New urdf for irb 1200 7/0.7

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@oliverek12: is this something that you would like to contribute? We'd be more than happy to merge it into the [ros-industrial/abb_experimental](https://github.com/ros-industrial/abb_experimental) repository.

**Comment by oliverek12** [comment]
Hello!
I am with an undergraduate group at Virginia Tech and we are starting to
work with an abb irb1200 7/0.7 arm. Once we get support for it tested out
soon I am planning to merging to the main abb repo fork. I just sent that
pull request in to the main fork instead of our own forked version, sorry.

Thanks,
Oliver Ebeling-Koning

**Comment by oliverek12** [comment]
Hello,

I am not sure for the correct people to contact for this and feel the ABB
ROS questions page might not be the right place for this. Any redirection
or help would be much appreciated!

I am running RobotStudio 5.61 with RobotWare 5.61 with an irb1200 setup
with the instructions on the ROS page. It seems that the issue below is in
RobotStudio or the abb_driver side:
I am working on getting ros support up and running for the ABB irb1200 7/07
robotic arm. Everything has been going fine except for trying to run the
irb1200 model in RobotStudio with the abb_driver running on the ROS side.
Joint_3 in the /joint_states topic is offset by a certain amount (seems to
be random from each launch of robotstudio) from what is displaying in
RobotStudio everytime. This is true in values and visual appearance of the
models. I have tried models other than the irb1200 on the Robot Studio side
without issues.

Thanks!
Oliver Ebeling-Koning

**Comment by gavanderhoorn** [comment]
I'd really recommend you send us an email on the [ROS-Industrial mailing list](https://groups.google.com/forum/#!forum/swri-ros-pkg-dev): there are far more users there, and the maintainers of the ABB packages will also receive your message.

Alternatively, a question on ROS Answers is actually also ok.

**Pull request closed without merging**
