### PR TITLE
travis: update to newest and switch to master

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
This also enabled `catkin_lint`, but that's more of a copy-paste. Not sure whether we want to do that in this repository.

**Comment by gavanderhoorn** [comment]
`catkin_lint` actually fails, but the build succeeds. Not sure what is going on there.

For now I'll ignore this, but I'll look into it.

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong: could you take a look?

**Review by Levi-Armstrong — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Thanks @Levi-Armstrong :+1:

**Pull request merged**
