### PR TITLE
Switch to Github Actions for CI

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

Still using `industrial_ci`, but now hosted by Github Actions.

Fairly minimal `matrix` build of Melodic and Noetic on Bionic and Focal. Might add Xenial+Kinetic back later (for Ubuntu ESM).

Runs here: [gavanderhoorn/abb/actions](https://github.com/gavanderhoorn/abb/actions).

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
For https://github.com/ros-industrial/ros_industrial_issues/issues/74

**Comment by gavanderhoorn** [comment]
CI is green, runs were successful.

Converting to PR.

**Review by NadiaHG — APPROVED** [review]
LGTM 👍🏽  

Thanks!

**Comment by gavanderhoorn** [comment]
Thanks @ipa-nhg

**Pull request merged**
